---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-config
  namespace: default
type: Opaque
data:
  # Base64 encoded CEPH configuration files
  # To create these: cat ceph.conf | base64 -w 0
  ceph.conf: |
    W2dsb2JhbF0KICAgIGF1dGhfY2xpZW50X3JlcXVpcmVkID0gY2VwaHgKICAgIGF1dGhfY2x1c3Rlcl9yZXF1aXJlZCA9IGNlcGh4CiAgICBhdXRoX3NlcnZpY2VfcmVxdWlyZWQgPSBjZXBoeAogICAgY2x1c3Rlcl9uZXR3b3JrID0gMTAuMTI4LjQuMS8yNAogICAgZnNpZCA9IDZjMWUzNzgwLThkZTktNDNjMS04ZmEwLTcyZmM0NGU2ZDhhOQogICAgbW9uX2FsbG93X3Bvb2xfZGVsZXRlID0gdHJ1ZQogICAgbW9uX2hvc3QgPSAxMC4xMjguNC4xIDEwLjEyOC40LjIgMTAuMTI4LjQuMwogICAgbXNfYmluZF9pcHY0ID0gdHJ1ZQogICAgbXNfYmluZF9pcHY2ID0gZmFsc2UKICAgIG9zZF9wb29sX2RlZmF1bHRfbWluX3NpemUgPSAyCiAgICBvc2RfcG9vbF9kZWZhdWx0X3NpemUgPSAzCiAgICBwdWJsaWNfbmV0d29yayA9IDEwLjEyOC40LjEvMjQKW2NsaWVudF0KICAgIGtleXJpbmcgPSAvZXRjL2NlcGgva2V5cmluZwo=
  
  # Base64 encoded keyring file
  # To create: cat keyring | base64 -w 0
  keyring: |
    W2NsaWVudC5hZG1pbl0KICAgIGtleSA9IEFRQ2trUE5ublkxN0N4QUFmM3dsZ2dqYlNmLy91TEhtR2l3TFVnPT0KICAgIGNhcHMgbWRzID0gImFsbG93ICoiCiAgICBjYXBzIG1nciA9ICJhbGxvdyAqIgogICAgY2FwcyBtb24gPSAiYWxsb3cgKiIKICAgIGNhcHMgb3NkID0gImFsbG93ICoiCg==

---
apiVersion: v1
kind: Secret
metadata:
  name: gpg-keys
  namespace: default
type: Opaque
data:
  # Base64 encoded GPG public key
  # To create: gpg --export --armor backup@example.com | base64 -w 0
  pubkey.asc: |
    LS0tLS1CRUdJTiBQR1AgUFVCTElDIEtFWSBCTE9DSy0tLS0tCgptUUVOQkdIU1pOc0JDQURYVnNnN09lUmFuVnJGTXRNT0JBdWJnV1NObWpMeGFRZ2g0RjFmWW5HTUFubz0KPXh3WFMKLS0tLS1FTkQgUEdQIFBVQkxJQyBLRVkgQkxPQ0stLS0tLQo=
  
  # Base64 encoded GPG trustdb (optional)
  # To create: cat ~/.gnupg/trustdb.gpg | base64 -w 0
  trustdb.gpg: |
    AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded MinIO credentials
  # To create: echo -n "your-access-key" | base64
  access-key: eW91ci1hY2Nlc3Mta2V5
  # To create: echo -n "your-secret-key" | base64  
  secret-key: eW91ci1zZWNyZXQta2V5